// Generated by Haxe 4.0.5
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var client_DataHandler = function() { };
client_DataHandler.__name__ = true;
client_DataHandler.getBookmarks = function() {
	var _g = [];
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	_g.push({ title : "First", links : ["http1","http2"], sumup : "Lorem ipsum", categories : [0,2], keywords : ["tag1","tag2"]});
	return _g;
};
var client_Main = function() { };
client_Main.__name__ = true;
client_Main.main = function() {
	ReactDOM.render({ $$typeof : $$tre, type : client_view_App, props : { }, key : null, ref : null},window.document.getElementById("app"));
};
var client_view_App = function(props) {
	React.Component.call(this,props);
};
client_view_App.__name__ = true;
client_view_App.__super__ = React.Component;
client_view_App.prototype = $extend(React.Component.prototype,{
	render: function() {
		return { $$typeof : $$tre, type : "div", props : { 'class' : "container", children : [{ $$typeof : $$tre, type : "div", props : { id : "navbar", 'class' : "row", children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "col-8", children : { $$typeof : $$tre, type : "input", props : { type : "text", placeholder : "Rechercher", 'class' : "col-12 navbar-item"}, key : null, ref : null}}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { 'class' : "col-4", children : { $$typeof : $$tre, type : "input", props : { type : "text", placeholder : "Catégories", 'class' : "col-12 navbar-item"}, key : null, ref : null}}, key : null, ref : null}]}, key : null, ref : null},this.getBookmarks()]}, key : null, ref : null};
	}
	,getBookmarks: function() {
		var _this = client_DataHandler.getBookmarks();
		var result = new Array(_this.length);
		var _g = 0;
		var _g1 = _this.length;
		while(_g < _g1) {
			var i = _g++;
			result[i] = { $$typeof : $$tre, type : client_view_BookmarkView, props : { data : _this[i]}, key : null, ref : null};
		}
		var bookmarks = result;
		var _this1 = util_ArrayUtil.split(bookmarks,3);
		var result1 = new Array(_this1.length);
		var _g2 = 0;
		var _g11 = _this1.length;
		while(_g2 < _g11) {
			var i1 = _g2++;
			result1[i1] = { $$typeof : $$tre, type : "div", props : { 'class' : "row", children : _this1[i1]}, key : null, ref : null};
		}
		var rows = result1;
		return { $$typeof : $$tre, type : "div", props : { children : rows}, key : null, ref : null};
	}
});
var client_view_BookmarkView = function(props) {
	React.Component.call(this,props);
	this.data = props.data;
	console.log("src/client/view/BookmarkView.hx:16:",this.data);
};
client_view_BookmarkView.__name__ = true;
client_view_BookmarkView.__super__ = React.Component;
client_view_BookmarkView.prototype = $extend(React.Component.prototype,{
	render: function() {
		var links = util_ArrayUtil.toSeparatedString(this.data.links,", ");
		var categories = util_ArrayUtil.toSeparatedString(this.data.categories,", ");
		var keywords = util_ArrayUtil.toSeparatedString(this.data.keywords,", ");
		return { $$typeof : $$tre, type : "div", props : { 'class' : "col-4", children : { $$typeof : $$tre, type : "div", props : { 'class' : "col-12 bookmark", children : [{ $$typeof : $$tre, type : "h1", props : { children : this.data.title}, key : null, ref : null},{ $$typeof : $$tre, type : "b", props : { children : "Résumé:"}, key : null, ref : null},{ $$typeof : $$tre, type : "p", props : { children : this.data.sumup}, key : null, ref : null},{ $$typeof : $$tre, type : "b", props : { children : "Liens:"}, key : null, ref : null},{ $$typeof : $$tre, type : "p", props : { children : links}, key : null, ref : null},{ $$typeof : $$tre, type : "b", props : { children : "Catégories:"}, key : null, ref : null},{ $$typeof : $$tre, type : "p", props : { children : categories}, key : null, ref : null},{ $$typeof : $$tre, type : "b", props : { children : "Mots-clés:"}, key : null, ref : null},{ $$typeof : $$tre, type : "p", props : { children : keywords}, key : null, ref : null}]}, key : null, ref : null}}, key : null, ref : null};
	}
});
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g3 = 0;
			var _g11 = o.length;
			while(_g3 < _g11) {
				var i = _g3++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str1 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str1.length != 2) {
			str1 += ", \n";
		}
		str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str1 += "\n" + s + "}";
		return str1;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var util_ArrayUtil = function() { };
util_ArrayUtil.__name__ = true;
util_ArrayUtil.split = function(array,count) {
	var ret = [];
	var start = 0;
	while(start < array.length) {
		ret.push(array.splice(start,count));
		start += count;
	}
	return ret;
};
util_ArrayUtil.toSeparatedString = function(array,separator) {
	var ret = "";
	var _g = 0;
	var _g1 = array.length - 1;
	while(_g < _g1) {
		var i = _g++;
		ret += Std.string(array[i]) + separator;
	}
	ret += Std.string(array[array.length - 1]);
	return ret;
};
String.__name__ = true;
Array.__name__ = true;
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
js_Boot.__toStr = ({ }).toString;
client_view_App.displayName = "App";
client_view_BookmarkView.displayName = "BookmarkView";
client_Main.main();
})({});
