// Generated by Haxe 4.0.5
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var client_Main = function() { };
client_Main.__name__ = true;
client_Main.main = function() {
	ReactDOM.render({ $$typeof : $$tre, type : client_view_App, props : { }, key : null, ref : null},window.document.getElementById("app"));
};
var client_model_util_Content = function() { };
client_model_util_Content.__name__ = true;
client_model_util_Content.GetLoremIpsum = function() {
	return "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam nibh metus, in auctor dui sollicitudin quis. Quisque convallis gravida tortor sed malesuada. Curabitur fringilla pulvinar magna, in fringilla diam consectetur sed. Morbi varius lectus et viverra finibus. Ut efficitur tristique sapien id lobortis. Morbi vulputate orci vitae elit pulvinar bibendum. In luctus pharetra quam, at consectetur dui placerat ut. In tempus ultricies mattis. Donec sodales lectus imperdiet, luctus mauris non, dapibus turpis. ";
};
var client_view_App = function(props) {
	React.Component.call(this,props);
};
client_view_App.__name__ = true;
client_view_App.__super__ = React.Component;
client_view_App.prototype = $extend(React.Component.prototype,{
	componentDidMount: function() {
		$(".fullscreen").each(function(index,element) {
			if((index & 1) == 1) {
				var element1 = element;
				element1.className += " own-bg-primary";
				return element1.className;
			} else {
				var element2 = element;
				element2.className += " own-bg-primary-light";
				return element2.className;
			}
		});
	}
	,render: function() {
		return { $$typeof : $$tre, type : "div", props : { children : [{ $$typeof : $$tre, type : client_view_Nav, props : { }, key : null, ref : null},{ $$typeof : $$tre, type : client_view_CurriculumChoice, props : { }, key : null, ref : null},{ $$typeof : $$tre, type : client_view_Presentation, props : { }, key : null, ref : null},{ $$typeof : $$tre, type : client_view_experiences_Experiences, props : { }, key : null, ref : null}]}, key : null, ref : null};
	}
});
var client_view_CurriculumChoice = function(props) {
	this.centerToContentIndex = 0;
	this.count = 10;
	React.Component.call(this,props);
	this.jquery = $(window.document);
	this.orders = [0,1,2];
	var _g = [];
	var _g1 = 0;
	var _g2 = this.count;
	while(_g1 < _g2) {
		var i = _g1++;
		var code = HxOverrides.cca("A",0) + i;
		_g.push(String.fromCodePoint(code));
	}
	this.content = _g;
};
client_view_CurriculumChoice.__name__ = true;
client_view_CurriculumChoice.__super__ = React.Component;
client_view_CurriculumChoice.prototype = $extend(React.Component.prototype,{
	componentDidMount: function() {
		var _gthis = this;
		var choiceDivs = $(".curriculum-choice > div");
		choiceDivs.on("webkitAnimationEnd animationend",null,function(e) {
			return choiceDivs.removeClass("invisible-fade-in");
		});
		choiceDivs.each(function(index,element) {
			return _gthis.generateContent(index,element);
		});
	}
	,render: function() {
		var f = $bind(this,this.onChoiceChanged);
		var tmp = function() {
			f(-1);
		};
		var f1 = $bind(this,this.onChoiceChanged);
		var tmp1 = function() {
			f1(1);
		};
		return { $$typeof : $$tre, type : "div", props : { 'class' : "fullscreen background", children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "h-full w-full flex flex-col justify-center items-center", children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "w-full flex justify-center items-center", children : [{ $$typeof : $$tre, type : "span", props : { onClick : tmp, 'class' : "material-icons ml-8 font-64", children : "arrow_back_ios"}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { 'class' : "curriculum-choice", children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "own-order-0"}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { 'class' : "own-order-1"}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { 'class' : "own-order-2"}, key : null, ref : null},"       "]}, key : null, ref : null},{ $$typeof : $$tre, type : "span", props : { onClick : tmp1, 'class' : "material-icons mr-8 font-64 interactible", children : "arrow_forward_ios"}, key : null, ref : null}]}, key : null, ref : null},{ $$typeof : $$tre, type : "h2", props : { 'class' : "text-center mt-4", children : "Normal"}, key : null, ref : null}]}, key : null, ref : null},{ $$typeof : $$tre, type : client_view_utilities_ScrollArrow, props : { }, key : null, ref : null}]}, key : null, ref : null};
	}
	,onChoiceChanged: function(delta) {
		var _gthis = this;
		var regex_r = new RegExp("own-order-[0-9]*","".split("u").join(""));
		var choices = $(".curriculum-choice > div");
		choices.removeClass("invisible-fade-in");
		this.centerToContentIndex -= delta;
		if(this.centerToContentIndex < 0) {
			this.centerToContentIndex = this.content.length - 1;
		} else if(this.centerToContentIndex >= this.content.length) {
			this.centerToContentIndex = 0;
		}
		var toUpdate = $(".own-order-" + (1 + delta)).addClass("invisible-fade-in").get(0);
		choices.each(function(index,element) {
			var classes = element.className;
			classes = classes.replace(regex_r,"");
			if((_gthis.orders[index] += delta) < 0) {
				_gthis.orders[index] = _gthis.orders.length - 1;
				_gthis.generateContent(_gthis.orders[index],element);
			} else if(_gthis.orders[index] >= _gthis.orders.length) {
				_gthis.orders[index] = 0;
				_gthis.generateContent(_gthis.orders[index],element);
			}
			classes += " own-order-" + _gthis.orders[index];
			return element.className = classes;
		});
	}
	,generateContent: function(index,element) {
		while(element.firstChild != null) element.removeChild(element.firstChild);
		var contentIndex = (this.centerToContentIndex + index - 1) % this.content.length;
		console.log("src/client/view/CurriculumChoice.hx:100:","" + index + " " + contentIndex + " " + Std.string(element));
		if(contentIndex < 0) {
			contentIndex = this.content.length - 1;
		}
		var node = window.document.createElement("h3");
		node.textContent = this.content[contentIndex];
		node.className = "text-center m-auto text-2xl";
		element.appendChild(node);
		return node;
	}
});
var client_view_Nav = function(props) {
	React.Component.call(this,props);
	this.jquery = $(window.document);
};
client_view_Nav.__name__ = true;
client_view_Nav.__super__ = React.Component;
client_view_Nav.prototype = $extend(React.Component.prototype,{
	render: function() {
		var f = $bind(this,this.onLanguageClicked);
		var tmp = function() {
			f(0);
		};
		var f1 = $bind(this,this.onLanguageClicked);
		var tmp1 = function() {
			f1(1);
		};
		return { $$typeof : $$tre, type : "div", props : { 'class' : "header z-50", children : { $$typeof : $$tre, type : "nav", props : { 'class' : "navbar navbar-primary", children : [{ $$typeof : $$tre, type : "a", props : { href : "#", 'class' : "navbar-brand", children : "Erik Kubiak"}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { id : "language", 'class' : "flex flex-row-reverse mr-4", children : [{ $$typeof : $$tre, type : "button", props : { onClick : tmp, 'class' : "interactible", children : { $$typeof : $$tre, type : "img", props : { src : "./images/french-flag.png", 'class' : "h-full"}, key : null, ref : null}}, key : null, ref : null},{ $$typeof : $$tre, type : "button", props : { onClick : tmp1, 'class' : "interactible", children : { $$typeof : $$tre, type : "img", props : { src : "./images/uk-flag.png", 'class' : "h-full"}, key : null, ref : null}}, key : null, ref : null}]}, key : null, ref : null}]}, key : null, ref : null}}, key : null, ref : null};
	}
	,onLanguageClicked: function(languageIndex) {
	}
});
var client_view_Presentation = function(props) {
	React.Component.call(this,props);
};
client_view_Presentation.__name__ = true;
client_view_Presentation.__super__ = React.Component;
client_view_Presentation.prototype = $extend(React.Component.prototype,{
	render: function() {
		return { $$typeof : $$tre, type : "div", props : { 'class' : "fullscreen flex justify-center items-center", children : { $$typeof : $$tre, type : "div", props : { 'class' : "h-75 w-75 rounded-md p-4 flex flex-col justify-center items-center", children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "w-full h-52 flex justify-center items-center mb-8", children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "h-52 w-40 p-0.5 bg-gradient-to-r from-second to-tertiary rounded-3xl", children : { $$typeof : $$tre, type : "div", props : { 'class' : "h-full w-full rounded-3xl overflow-hidden", children : { $$typeof : $$tre, type : "img", props : { src : "./images/face.png", 'class' : "h-full"}, key : null, ref : null}}, key : null, ref : null}}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { 'class' : "w-full h-full flex flex-col justify-center items-center", children : [{ $$typeof : $$tre, type : "h3", props : { 'class' : "w-full pl-4 mb-4", children : " Erik Kubiak - Ingénieur"}, key : null, ref : null},{ $$typeof : $$tre, type : "p", props : { 'class' : "w-full h-full align-middle text-justify pl-4 pr-4", children : client_model_util_Content.GetLoremIpsum()}, key : null, ref : null}]}, key : null, ref : null}]}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { 'class' : "w-full", children : { $$typeof : $$tre, type : "p", props : { 'class' : "w-full text-justify pr-4", children : client_model_util_Content.GetLoremIpsum()}, key : null, ref : null}}, key : null, ref : null}]}, key : null, ref : null}}, key : null, ref : null};
	}
});
var client_view_experiences_ExperienceItem = function(props) {
	React.Component.call(this,props);
};
client_view_experiences_ExperienceItem.__name__ = true;
client_view_experiences_ExperienceItem.__super__ = React.Component;
client_view_experiences_ExperienceItem.prototype = $extend(React.Component.prototype,{
	render: function() {
		return { $$typeof : $$tre, type : "div", props : { children : { $$typeof : $$tre, type : "div", props : { 'class' : "fullscreen", children : { $$typeof : $$tre, type : "div", props : { 'class' : "experience-item h-full w-full flex justify-center items-center", children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "h-full w-50 flex justify-center items-center", children : { $$typeof : $$tre, type : "div", props : { 'class' : "column-highlight h-full w-2/3 flex flex-col justify-center items-center p-8", children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "w-full flex mb-1", children : [{ $$typeof : $$tre, type : "h3", props : { 'class' : "flex-grow", children : "Poste"}, key : null, ref : null},{ $$typeof : $$tre, type : "h3", props : { 'class' : "flex-grow-0", children : " 2019 - 2021"}, key : null, ref : null}]}, key : null, ref : null},{ $$typeof : $$tre, type : "h4", props : { 'class' : "ml-8 w-full mb-", children : "Entreprise"}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { 'class' : "w-full text-justify", children : { $$typeof : $$tre, type : "p", props : { children : client_model_util_Content.GetLoremIpsum()}, key : null, ref : null}}, key : null, ref : null}]}, key : null, ref : null}}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { 'class' : "h-full w-50 flex experience-item-image", children : { $$typeof : $$tre, type : "img", props : { src : "./images/test.png", 'class' : "h-full w-auto"}, key : null, ref : null}}, key : null, ref : null}]}, key : null, ref : null}}, key : null, ref : null}}, key : null, ref : null};
	}
});
var client_view_experiences_Experiences = function(props) {
	React.Component.call(this,props);
};
client_view_experiences_Experiences.__name__ = true;
client_view_experiences_Experiences.__super__ = React.Component;
client_view_experiences_Experiences.prototype = $extend(React.Component.prototype,{
	componentDidMount: function() {
		$(".experience-item").each(function(index,element) {
			if((index & 1) == 1) {
				var element1 = element;
				element1.className += " flex-row-reverse";
				return element1.className;
			} else {
				var element2 = element;
				element2.className += " flex-row";
				return element2.className;
			}
		});
	}
	,render: function() {
		return { $$typeof : $$tre, type : "div", props : { children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "fullscreen", children : [{ $$typeof : $$tre, type : "div", props : { 'class' : "h-full w-full flex justify-center items-center", children : { $$typeof : $$tre, type : "h1", props : { 'class' : "text-tertiary", children : "Experiences"}, key : null, ref : null}}, key : null, ref : null},{ $$typeof : $$tre, type : client_view_utilities_ScrollArrow, props : { }, key : null, ref : null}]}, key : null, ref : null},{ $$typeof : $$tre, type : client_view_experiences_ExperienceItem, props : { }, key : null, ref : null},{ $$typeof : $$tre, type : client_view_experiences_ExperienceItem, props : { }, key : null, ref : null},{ $$typeof : $$tre, type : client_view_experiences_ExperienceItem, props : { }, key : null, ref : null},{ $$typeof : $$tre, type : client_view_experiences_ExperienceItem, props : { }, key : null, ref : null}]}, key : null, ref : null};
	}
});
var client_view_utilities_ScrollArrow = function(props) {
	React.Component.call(this,props);
};
client_view_utilities_ScrollArrow.__name__ = true;
client_view_utilities_ScrollArrow.__super__ = React.Component;
client_view_utilities_ScrollArrow.prototype = $extend(React.Component.prototype,{
	render: function() {
		return { $$typeof : $$tre, type : "div", props : { 'class' : "scroll-arrow", children : { $$typeof : $$tre, type : "span", props : { 'class' : "bouncing-arrow material-icons", children : "expand_more"}, key : null, ref : null}}, key : null, ref : null};
	}
});
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g3 = 0;
			var _g11 = o.length;
			while(_g3 < _g11) {
				var i = _g3++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str1 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str1.length != 2) {
			str1 += ", \n";
		}
		str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str1 += "\n" + s + "}";
		return str1;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
if( String.fromCodePoint == null ) String.fromCodePoint = function(c) { return c < 0x10000 ? String.fromCharCode(c) : String.fromCharCode((c>>10)+0xD7C0)+String.fromCharCode((c&0x3FF)+0xDC00); }
String.__name__ = true;
Array.__name__ = true;
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
js_Boot.__toStr = ({ }).toString;
client_view_App.displayName = "App";
client_view_CurriculumChoice.displayName = "CurriculumChoice";
client_view_Nav.displayName = "Nav";
client_view_Presentation.displayName = "Presentation";
client_view_experiences_ExperienceItem.displayName = "ExperienceItem";
client_view_experiences_Experiences.displayName = "Experiences";
client_view_utilities_ScrollArrow.displayName = "ScrollArrow";
client_Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
